Feature/test page
amida-tech/qtc-web-ui pull request #5
Opened 2019-07-08 15:20 UTC by hmayenve

# Name of Feature 
`feature/test-page`
## Description
### Related Tickets

- [QTC-166](https://jira.amida.com/browse/QTC-166)

### How Things Worked (or Didn't) Before This PR
There want's a page for running DBQ tests on dbq

### How Things Work Now
A new page is create to upload a mapping and run dbq_tests on it.

## How to Test
- `npm start`
- `localhost:1776/test`

## Readiness

1. [ ] This PR has full test coverage (If this PR fixes a bug, you _must_ add test cases respresentative of the bug).
2. [ ] This PR passes all automated tests.
3. [ ] This PR has no linting errors.
4. [ ] This PR has no hardcoded UI strings or other obvious issues.
5. [ ] In addition to testing my changes while running this code via `npm start`, I tested my changes while running this code on my machine via `npm run build-prod-start` (necessary because the latter command mimics production).
6. [ ] This PR's changes to configuration files have been documented in all appropriate places (such as but not limited to README.md), if applicable.
7. [ ] This PR's required changes outside of the scope of this repository have been documented in this pull request.

2019-07-16 20:38 UTC, puckybreg requested changes
Left a few small comments. I think what might be the best process is for you to update from develop and then read through @mountHouli's comments on Elizabeth's Navigation PR because I think many of the comments will be identical.

2019-07-16 20:38 UTC, puckybreg commented on src/components/FileUpload.jsx
> +const LOCAL_API_URL = `http://127.0.0.1:5000/test_dbq`
Let's set both of these in the `config` and request them from there

2019-07-16 20:38 UTC, puckybreg commented on src/components/FileUpload.jsx
> +import 'styles/qtcstyles.scss'
An update from develop will change this but I believe it is now called just `styles`
```suggestion
import 'styles/styles.scss'
```

2019-07-16 20:38 UTC, puckybreg commented on src/components/FileUpload.jsx
> +        this.handleUpload = this.handleUpload.bind(this);
See @mountHouli  comments about binding class functions https://github.com/amida-tech/qtc-web-ui/pull/4#discussion_r299716547

2019-07-16 20:38 UTC, puckybreg commented on src/components/FileUpload.jsx
> +            <div className='app-page' id='test-page-div'>
See @mountHouli comments about unused ids https://github.com/amida-tech/qtc-web-ui/pull/4#discussion_r299716003

2019-07-16 20:38 UTC, puckybreg commented on src/components/FileUpload.jsx
> +                Please enter a DBQ number corresponding to the mapping file you would like to test.
I think you should put this text in a `<p/>` div

2019-08-27 18:28 UTC, hmayenve commented
Made updates

2019-08-30 20:45 UTC, puckybreg approved these changes
Great Work @hmayenve 🏅

2019-08-30 20:45 UTC, puckybreg commented on src/components/TestPage.jsx
> +  resetForm = () => {
This works great!

2019-08-30 20:45 UTC, puckybreg commented on src/components/TestPage.jsx
> +        if (error){
Just a note, no action required, but if you don't have the API running, The error that you get "Cannot POST" doesn't get caught by this conditional

2019-09-03 13:06 UTC, merged